name: Create Release

on:
  workflow_run:
    workflows: ["Create Tag from version.h"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio

      - name: Install platformIO libraries
        run: pio lib install
        
      - name: Build firmware (Release, no logging)
        run: platformio run -e release

      - name: Create Gerber zip
        run: |
          mkdir -p dist
          zip -j dist/Gerber.zip hardware/kicad/CoffeeGrinder/production/*.csv hardware/kicad/CoffeeGrinder/production/*.zip hardware/kicad/CoffeeGrinder/production/*.ipc

      - name: Create STL zip
        run: |
          mkdir -p dist
          zip -j dist/STL.zip hardware/stl/**/*.stl

      - name: Get latest tag
        id: get_tag
        run: |
          tag=$(git describe --tags --abbrev=0)
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Upload firmware and STLs
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          name: Release ${{ steps.get_tag.outputs.tag }}
          body: |
            Automated release for version ${{ steps.get_tag.outputs.tag }}
          files: |
            .pio/build/*/*.bin
            dist/STL.zip
            dist/Gerber.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete older releases (keep last 2)
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 2
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}